# Generated by Django 5.0.6 on 2024-06-08 15:11

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Debt',
            fields=[
                ('name', models.CharField(max_length=255)),
                ('governmentId', models.CharField(max_length=20)),
                ('email', models.EmailField(max_length=254)),
                ('debtAmount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('debtDueDate', models.DateField()),
                ('debtID', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
            ],
        ),
    ]
